unit udmImpCI;

interface

uses
  SysUtils, Classes, FMTBcd, ppArchiv, ppBands, Provider, SqlExpr, DB,
  DBClient, ppParameter, ppModule, raCodMod, ppCtrls, ppVar, ppPrnabl,
  ppClass, ppCache, ppProd, ppReport, ppComm, ppRelatv, ppDB, ppDBPipe;

type
  TdmImpCI = class(TDataModule)
    pplItenOrc: TppDBPipeline;
    rptOrc_00: TppReport;
    ppHeaderBand1: TppHeaderBand;
    ppLabel21: TppLabel;
    ppLine5: TppLine;
    ppLine6: TppLine;
    ppLabel22: TppLabel;
    ppLabel23: TppLabel;
    ppLabel24: TppLabel;
    ppSystemVariable2: TppSystemVariable;
    ppLine7: TppLine;
    ppLabel25: TppLabel;
    ppLabel30: TppLabel;
    ppLabel33: TppLabel;
    ppLabel34: TppLabel;
    ppLabel35: TppLabel;
    ppLabel36: TppLabel;
    ppLine8: TppLine;
    ppLabel41: TppLabel;
    ppLabel42: TppLabel;
    ppLabel45: TppLabel;
    ppLabel47: TppLabel;
    ppLabel49: TppLabel;
    ppLabel50: TppLabel;
    ppLabel51: TppLabel;
    ppLabel52: TppLabel;
    ppLabel53: TppLabel;
    ppLabel54: TppLabel;
    ppDBText13: TppDBText;
    ppDBText15: TppDBText;
    ppDBText16: TppDBText;
    ppDBText17: TppDBText;
    ppDBText18: TppDBText;
    ppDBText19: TppDBText;
    ppDBText21: TppDBText;
    ppDBText22: TppDBText;
    ppDBText23: TppDBText;
    ppDBText24: TppDBText;
    ppDBText20: TppDBText;
    ppDBText25: TppDBText;
    ppDBText26: TppDBText;
    ppLabel27: TppLabel;
    ppDBText32: TppDBText;
    ppLabel26: TppLabel;
    ppDBText33: TppDBText;
    ppDetailBand1: TppDetailBand;
    ppDBText7: TppDBText;
    ppDBText8: TppDBText;
    ppDBText9: TppDBText;
    ppDBText10: TppDBText;
    ppDBText11: TppDBText;
    ppDBText12: TppDBText;
    ppFooterBand1: TppFooterBand;
    ppLabel29: TppLabel;
    ppDBText14: TppDBText;
    ppLabel31: TppLabel;
    ppDBText27: TppDBText;
    ppLabel32: TppLabel;
    ppDBText28: TppDBText;
    ppLabel37: TppLabel;
    ppLabel38: TppLabel;
    ppLabel40: TppLabel;
    ppDBText29: TppDBText;
    ppDBText30: TppDBText;
    ppDBText31: TppDBText;
    ppLabel28: TppLabel;
    ppDBText35: TppDBText;
    ppLabel43: TppLabel;
    ppDBText34: TppDBText;
    ppLabel44: TppLabel;
    ppDBText36: TppDBText;
    ppLabel39: TppLabel;
    ppDBText37: TppDBText;
    ppLabel46: TppLabel;
    raCodeModule2: TraCodeModule;
    ppParameterList2: TppParameterList;
    dsItensOrc: TDataSource;
    dsOrcamento: TDataSource;
    cdsOrcamento: TClientDataSet;
    cdsOrcamentoCODIGO_VENDA: TIntegerField;
    cdsOrcamentoVENDEDOR_VENDA: TIntegerField;
    cdsOrcamentoPARCEIRO_VENDA: TIntegerField;
    cdsOrcamentoCLIENTE_VENDA: TIntegerField;
    cdsOrcamentoPROPRIEDADE_VENDA: TIntegerField;
    cdsOrcamentoNOMECLIENTE_VENDA: TStringField;
    cdsOrcamentoDATA_VENDA: TDateField;
    cdsOrcamentoEXCLUSAO_VENDA: TDateField;
    cdsOrcamentoHORA_VENDA: TStringField;
    cdsOrcamentoFATURA_VENDA: TFMTBCDField;
    cdsOrcamentoDESCONTO_VENDA: TFMTBCDField;
    cdsOrcamentoDESCON_ESP_VENDA: TFMTBCDField;
    cdsOrcamentoCPAGAMENTO_VENDA: TFMTBCDField;
    cdsOrcamentoCHAVE_VENDA: TStringField;
    cdsOrcamentoCAIXA_VENDA: TFMTBCDField;
    cdsOrcamentoTIPO_PRECO_VENDA: TStringField;
    cdsOrcamentoCFOP_VENDA: TStringField;
    cdsOrcamentoNOTAFISCAL_VENDA: TIntegerField;
    cdsOrcamentoSERIE_VENDA: TStringField;
    cdsOrcamentoCONFIRMA_VENDA: TStringField;
    cdsOrcamentoEMISSAO_VENDA: TDateField;
    cdsOrcamentoDATASAIDA_VENDA: TDateField;
    cdsOrcamentoHORASAIDA_VENDA: TStringField;
    cdsOrcamentoVALORNOTA_VENDA: TFMTBCDField;
    cdsOrcamentoBASEICMS_VENDA: TFMTBCDField;
    cdsOrcamentoICMS_VENDA: TFMTBCDField;
    cdsOrcamentoBASEICMSSB_VENDA: TFMTBCDField;
    cdsOrcamentoICMSSB_VENDA: TFMTBCDField;
    cdsOrcamentoIPI_VENDA: TFMTBCDField;
    cdsOrcamentoTRANSPORTA_VENDA: TIntegerField;
    cdsOrcamentoPESOBRUTO_VENDA: TFMTBCDField;
    cdsOrcamentoPESOLIQUIDO_VENDA: TFMTBCDField;
    cdsOrcamentoOBSERVACAO_VENDA: TStringField;
    cdsOrcamentoPARCELAS_VENDA: TIntegerField;
    cdsOrcamentoVALOR01_VENDA: TFMTBCDField;
    cdsOrcamentoVALOR02_VENDA: TFMTBCDField;
    cdsOrcamentoVALOR03_VENDA: TFMTBCDField;
    cdsOrcamentoVALOR04_VENDA: TFMTBCDField;
    cdsOrcamentoVALOR05_VENDA: TFMTBCDField;
    cdsOrcamentoVALOR06_VENDA: TFMTBCDField;
    cdsOrcamentoVALOR07_VENDA: TFMTBCDField;
    cdsOrcamentoVALOR08_VENDA: TFMTBCDField;
    cdsOrcamentoVALOR09_VENDA: TFMTBCDField;
    cdsOrcamentoVALOR10_VENDA: TFMTBCDField;
    cdsOrcamentoVALOR11_VENDA: TFMTBCDField;
    cdsOrcamentoVALOR12_VENDA: TFMTBCDField;
    cdsOrcamentoVALOR13_VENDA: TFMTBCDField;
    cdsOrcamentoVALOR14_VENDA: TFMTBCDField;
    cdsOrcamentoVALOR15_VENDA: TFMTBCDField;
    cdsOrcamentoVENCIMEN01_VENDA: TDateField;
    cdsOrcamentoVENCIMEN02_VENDA: TDateField;
    cdsOrcamentoVENCIMEN03_VENDA: TDateField;
    cdsOrcamentoVENCIMEN04_VENDA: TDateField;
    cdsOrcamentoVENCIMEN05_VENDA: TDateField;
    cdsOrcamentoVENCIMEN06_VENDA: TDateField;
    cdsOrcamentoVENCIMEN07_VENDA: TDateField;
    cdsOrcamentoVENCIMEN08_VENDA: TDateField;
    cdsOrcamentoVENCIMEN09_VENDA: TDateField;
    cdsOrcamentoVENCIMEN10_VENDA: TDateField;
    cdsOrcamentoVENCIMEN11_VENDA: TDateField;
    cdsOrcamentoVENCIMEN12_VENDA: TDateField;
    cdsOrcamentoVENCIMEN13_VENDA: TDateField;
    cdsOrcamentoVENCIMEN14_VENDA: TDateField;
    cdsOrcamentoVENCIMEN15_VENDA: TDateField;
    cdsOrcamentoCOMISSAO_VENDA: TFMTBCDField;
    cdsOrcamentoTIPO_VENDA: TStringField;
    cdsOrcamentoTIPO1_VENDA: TStringField;
    cdsOrcamentoDEVOLVE_VENDA: TStringField;
    cdsOrcamentoENTREGA_VENDA: TStringField;
    cdsOrcamentoTROCO_VENDA: TFMTBCDField;
    cdsOrcamentoFRETE_VENDA: TFMTBCDField;
    cdsOrcamentoSEGURO_VENDA: TFMTBCDField;
    cdsOrcamentoOUTROS_VENDA: TFMTBCDField;
    cdsOrcamentoROMANEIO_VENDA: TIntegerField;
    cdsOrcamentoPLACASAIDA_VENDA: TStringField;
    cdsOrcamentoESTADOSAIDA_VENDA: TStringField;
    cdsOrcamentoNRFATURA_VENDA: TIntegerField;
    cdsOrcamentoAUTONOMO_VENDA: TStringField;
    cdsOrcamentoEXPORTADO_VENDA: TStringField;
    cdsOrcamentoTIPO_DOC_VENDA: TStringField;
    cdsOrcamentoINFOADICIONA_VENDA: TStringField;
    cdsOrcamentoMACHO_4_VENDA: TIntegerField;
    cdsOrcamentoMACHO_4_12_VENDA: TIntegerField;
    cdsOrcamentoMACHO_12_24_VENDA: TIntegerField;
    cdsOrcamentoMACHO_24_36_VENDA: TIntegerField;
    cdsOrcamentoMACHO_M36_VENDA: TIntegerField;
    cdsOrcamentoFEMEA_4_VENDA: TIntegerField;
    cdsOrcamentoFEMEA_4_12_VENDA: TIntegerField;
    cdsOrcamentoFEMEA_12_24_VENDA: TIntegerField;
    cdsOrcamentoFEMEA_24_36_VENDA: TIntegerField;
    cdsOrcamentoFEMEA_M36_VENDA: TIntegerField;
    cdsOrcamentoBUFALOS_VENDA: TIntegerField;
    cdsOrcamentoCAPRINOS_VENDA: TIntegerField;
    cdsOrcamentoOVINOS_VENDA: TIntegerField;
    cdsOrcamentoSUINOS_VENDA: TIntegerField;
    cdsOrcamentoTROCA_VENDA: TIntegerField;
    cdsOrcamentoOS_VENDA: TIntegerField;
    cdsOrcamentoCNPJCLIENTE_VENDA: TStringField;
    cdsOrcamentoRGCLIENTE_VENDA: TStringField;
    cdsOrcamentoENDCLIENTE_VENDA: TStringField;
    cdsOrcamentoBAICLIENTE_VENDA: TStringField;
    cdsOrcamentoCIDCLIENTE_VENDA: TStringField;
    cdsOrcamentoESTCLIENTE_VENDA: TStringField;
    cdsOrcamentoCEPCLIENTE_VENDA: TStringField;
    cdsOrcamentoFONECLIENTE_VENDA: TStringField;
    cdsOrcamentoCARNE_VENDA: TStringField;
    cdsOrcamentoUSUARIO_VENDA: TStringField;
    cdsOrcamentoUSUALTERA_VENDA: TStringField;
    cdsOrcamentoCOD_EMPRESA: TIntegerField;
    cdsOrcamentoOBS1: TStringField;
    cdsOrcamentoOBS2: TStringField;
    cdsOrcamentoOBS3: TStringField;
    cdsOrcamentoOBS4: TStringField;
    cdsOrcamentoVALOR_BRUTO: TFMTBCDField;
    cdsOrcamentoDESC_PORC: TFMTBCDField;
    cdsOrcamentoCGC_EMP: TStringField;
    cdsOrcamentoINSCRICAO_EMP: TStringField;
    cdsOrcamentoEMPRESA: TStringField;
    cdsOrcamentoEND_EMPRESA: TStringField;
    cdsOrcamentoCIDADE_EMP: TStringField;
    cdsOrcamentoFONE_EMP: TStringField;
    cdsOrcamentoNOME_VENDEDOR: TStringField;
    cdsOrcamentoFORMA_PAGAMENTO: TStringField;
    cdsOrcamentoDESCRICAO_PRO: TStringField;
    cdsOrcamentoBAIRRO_PRO: TStringField;
    cdsOrcamentoCEP_PRO: TStringField;
    cdsOrcamentoCIDADE_PRO: TStringField;
    cdsOrcamentoFONE_PRO: TStringField;
    cdsOrcamentoESTADO_PRO: TStringField;
    cdsOrcamentoINSCEST_PRO: TStringField;
    cdsOrcamentoCODIGO_CLIENTE: TIntegerField;
    cdsOrcamentoNOME_CLIENTE: TStringField;
    cdsOrcamentoFANTASIA_CLIENTE: TStringField;
    cdsOrcamentoCNPJ_CLIENTE: TStringField;
    cdsOrcamentoNOME_CIDADE: TStringField;
    cdsOrcamentoCOB_NOME_CIDADE: TStringField;
    cdsOrcamentoCOB_ENDERECO_CLIENTE: TStringField;
    cdsOrcamentoBANCO1_CLIENTE: TStringField;
    cdsOrcamentoENDERECO_CLIENTE: TStringField;
    cdsOrcamentoBAIRRO_CLIENTE: TStringField;
    cdsOrcamentoCEP_CLIENTE: TStringField;
    cdsOrcamentoCIDADE_CLIENTE: TIntegerField;
    cdsOrcamentoTELEFONE_CLIENTE: TStringField;
    cdsOrcamentoESTADO_CLIENTE: TStringField;
    cdsOrcamentoINSCRICAO_CLIENTE: TStringField;
    cdsOrcamentoqryItensOrc: TDataSetField;
    cdsItensOrc: TClientDataSet;
    cdsItensOrcID_VENDA_ITEM: TIntegerField;
    cdsItensOrcCODIGO_IVENDA: TIntegerField;
    cdsItensOrcPRODUTO_IVENDA: TIntegerField;
    cdsItensOrcDESCRICAO_IVENDAS: TStringField;
    cdsItensOrcVALORBRUTO_IVENDAS: TFMTBCDField;
    cdsItensOrcQUANTIDADE_IVENDAS: TFMTBCDField;
    cdsItensOrcGRADE_IVENDAS: TStringField;
    cdsItensOrcPROMOCAO_IVENDAS: TStringField;
    cdsItensOrcFABRICA_IVENDAS: TStringField;
    cdsItensOrcSERIE_IVENDAS: TStringField;
    cdsItensOrcDESCONTO_IVENDAS: TFMTBCDField;
    cdsItensOrcICM_IVENDAS: TFMTBCDField;
    cdsItensOrcIPI_IVENDAS: TFMTBCDField;
    cdsItensOrcREDUTOR_IVENDAS: TFMTBCDField;
    cdsItensOrcTRIBUTACAO_IVENDAS: TStringField;
    cdsItensOrcFISCAL_IVENDAS: TStringField;
    cdsItensOrcGARANTIA_IVENDAS: TStringField;
    cdsItensOrcTECNICO_IVENDAS: TIntegerField;
    cdsItensOrcALTURA_IVENDAS: TFMTBCDField;
    cdsItensOrcLARGURA_IVENDAS: TFMTBCDField;
    cdsItensOrcCOMPRIMENTO_VENDAS: TFMTBCDField;
    cdsItensOrcQTDE_VENDAS: TIntegerField;
    cdsItensOrcCOMPLEMENTO: TStringField;
    cdsItensOrcCOD_EMPRESA: TIntegerField;
    cdsItensOrcCLASSE_IVENDA: TStringField;
    cdsItensOrcVALORTOTAL: TFMTBCDField;
    cdsItensOrcFABRICA_PRODUTO: TIntegerField;
    cdsItensOrcFABRICANTE_PRODUTO: TStringField;
    cdsItensOrcUNIDADE_PRODUTO: TStringField;
    cdsItensOrcCODIGO_GRADE: TStringField;
    cdsItensOrcPRECO_CUSTO_PRODUTO: TFMTBCDField;
    qryOrcamento: TSQLQuery;
    qryOrcamentoCODIGO_VENDA: TIntegerField;
    qryOrcamentoVENDEDOR_VENDA: TIntegerField;
    qryOrcamentoPARCEIRO_VENDA: TIntegerField;
    qryOrcamentoCLIENTE_VENDA: TIntegerField;
    qryOrcamentoPROPRIEDADE_VENDA: TIntegerField;
    qryOrcamentoNOMECLIENTE_VENDA: TStringField;
    qryOrcamentoDATA_VENDA: TDateField;
    qryOrcamentoEXCLUSAO_VENDA: TDateField;
    qryOrcamentoHORA_VENDA: TStringField;
    qryOrcamentoFATURA_VENDA: TFMTBCDField;
    qryOrcamentoDESCONTO_VENDA: TFMTBCDField;
    qryOrcamentoDESCON_ESP_VENDA: TFMTBCDField;
    qryOrcamentoCPAGAMENTO_VENDA: TFMTBCDField;
    qryOrcamentoCHAVE_VENDA: TStringField;
    qryOrcamentoCAIXA_VENDA: TFMTBCDField;
    qryOrcamentoTIPO_PRECO_VENDA: TStringField;
    qryOrcamentoCFOP_VENDA: TStringField;
    qryOrcamentoNOTAFISCAL_VENDA: TIntegerField;
    qryOrcamentoSERIE_VENDA: TStringField;
    qryOrcamentoCONFIRMA_VENDA: TStringField;
    qryOrcamentoEMISSAO_VENDA: TDateField;
    qryOrcamentoDATASAIDA_VENDA: TDateField;
    qryOrcamentoHORASAIDA_VENDA: TStringField;
    qryOrcamentoVALORNOTA_VENDA: TFMTBCDField;
    qryOrcamentoBASEICMS_VENDA: TFMTBCDField;
    qryOrcamentoICMS_VENDA: TFMTBCDField;
    qryOrcamentoBASEICMSSB_VENDA: TFMTBCDField;
    qryOrcamentoICMSSB_VENDA: TFMTBCDField;
    qryOrcamentoIPI_VENDA: TFMTBCDField;
    qryOrcamentoTRANSPORTA_VENDA: TIntegerField;
    qryOrcamentoPESOBRUTO_VENDA: TFMTBCDField;
    qryOrcamentoPESOLIQUIDO_VENDA: TFMTBCDField;
    qryOrcamentoOBSERVACAO_VENDA: TStringField;
    qryOrcamentoPARCELAS_VENDA: TIntegerField;
    qryOrcamentoVALOR01_VENDA: TFMTBCDField;
    qryOrcamentoVALOR02_VENDA: TFMTBCDField;
    qryOrcamentoVALOR03_VENDA: TFMTBCDField;
    qryOrcamentoVALOR04_VENDA: TFMTBCDField;
    qryOrcamentoVALOR05_VENDA: TFMTBCDField;
    qryOrcamentoVALOR06_VENDA: TFMTBCDField;
    qryOrcamentoVALOR07_VENDA: TFMTBCDField;
    qryOrcamentoVALOR08_VENDA: TFMTBCDField;
    qryOrcamentoVALOR09_VENDA: TFMTBCDField;
    qryOrcamentoVALOR10_VENDA: TFMTBCDField;
    qryOrcamentoVALOR11_VENDA: TFMTBCDField;
    qryOrcamentoVALOR12_VENDA: TFMTBCDField;
    qryOrcamentoVALOR13_VENDA: TFMTBCDField;
    qryOrcamentoVALOR14_VENDA: TFMTBCDField;
    qryOrcamentoVALOR15_VENDA: TFMTBCDField;
    qryOrcamentoVENCIMEN01_VENDA: TDateField;
    qryOrcamentoVENCIMEN02_VENDA: TDateField;
    qryOrcamentoVENCIMEN03_VENDA: TDateField;
    qryOrcamentoVENCIMEN04_VENDA: TDateField;
    qryOrcamentoVENCIMEN05_VENDA: TDateField;
    qryOrcamentoVENCIMEN06_VENDA: TDateField;
    qryOrcamentoVENCIMEN07_VENDA: TDateField;
    qryOrcamentoVENCIMEN08_VENDA: TDateField;
    qryOrcamentoVENCIMEN09_VENDA: TDateField;
    qryOrcamentoVENCIMEN10_VENDA: TDateField;
    qryOrcamentoVENCIMEN11_VENDA: TDateField;
    qryOrcamentoVENCIMEN12_VENDA: TDateField;
    qryOrcamentoVENCIMEN13_VENDA: TDateField;
    qryOrcamentoVENCIMEN14_VENDA: TDateField;
    qryOrcamentoVENCIMEN15_VENDA: TDateField;
    qryOrcamentoCOMISSAO_VENDA: TFMTBCDField;
    qryOrcamentoTIPO_VENDA: TStringField;
    qryOrcamentoTIPO1_VENDA: TStringField;
    qryOrcamentoDEVOLVE_VENDA: TStringField;
    qryOrcamentoENTREGA_VENDA: TStringField;
    qryOrcamentoTROCO_VENDA: TFMTBCDField;
    qryOrcamentoFRETE_VENDA: TFMTBCDField;
    qryOrcamentoSEGURO_VENDA: TFMTBCDField;
    qryOrcamentoOUTROS_VENDA: TFMTBCDField;
    qryOrcamentoROMANEIO_VENDA: TIntegerField;
    qryOrcamentoPLACASAIDA_VENDA: TStringField;
    qryOrcamentoESTADOSAIDA_VENDA: TStringField;
    qryOrcamentoNRFATURA_VENDA: TIntegerField;
    qryOrcamentoAUTONOMO_VENDA: TStringField;
    qryOrcamentoEXPORTADO_VENDA: TStringField;
    qryOrcamentoTIPO_DOC_VENDA: TStringField;
    qryOrcamentoINFOADICIONA_VENDA: TStringField;
    qryOrcamentoMACHO_4_VENDA: TIntegerField;
    qryOrcamentoMACHO_4_12_VENDA: TIntegerField;
    qryOrcamentoMACHO_12_24_VENDA: TIntegerField;
    qryOrcamentoMACHO_24_36_VENDA: TIntegerField;
    qryOrcamentoMACHO_M36_VENDA: TIntegerField;
    qryOrcamentoFEMEA_4_VENDA: TIntegerField;
    qryOrcamentoFEMEA_4_12_VENDA: TIntegerField;
    qryOrcamentoFEMEA_12_24_VENDA: TIntegerField;
    qryOrcamentoFEMEA_24_36_VENDA: TIntegerField;
    qryOrcamentoFEMEA_M36_VENDA: TIntegerField;
    qryOrcamentoBUFALOS_VENDA: TIntegerField;
    qryOrcamentoCAPRINOS_VENDA: TIntegerField;
    qryOrcamentoOVINOS_VENDA: TIntegerField;
    qryOrcamentoSUINOS_VENDA: TIntegerField;
    qryOrcamentoTROCA_VENDA: TIntegerField;
    qryOrcamentoOS_VENDA: TIntegerField;
    qryOrcamentoCNPJCLIENTE_VENDA: TStringField;
    qryOrcamentoRGCLIENTE_VENDA: TStringField;
    qryOrcamentoENDCLIENTE_VENDA: TStringField;
    qryOrcamentoBAICLIENTE_VENDA: TStringField;
    qryOrcamentoCIDCLIENTE_VENDA: TStringField;
    qryOrcamentoESTCLIENTE_VENDA: TStringField;
    qryOrcamentoCEPCLIENTE_VENDA: TStringField;
    qryOrcamentoFONECLIENTE_VENDA: TStringField;
    qryOrcamentoCARNE_VENDA: TStringField;
    qryOrcamentoUSUARIO_VENDA: TStringField;
    qryOrcamentoUSUALTERA_VENDA: TStringField;
    qryOrcamentoCOD_EMPRESA: TIntegerField;
    qryOrcamentoOBS1: TStringField;
    qryOrcamentoOBS2: TStringField;
    qryOrcamentoOBS3: TStringField;
    qryOrcamentoOBS4: TStringField;
    qryOrcamentoVALOR_BRUTO: TFMTBCDField;
    qryOrcamentoDESC_PORC: TFMTBCDField;
    qryOrcamentoCGC_EMP: TStringField;
    qryOrcamentoINSCRICAO_EMP: TStringField;
    qryOrcamentoEMPRESA: TStringField;
    qryOrcamentoEND_EMPRESA: TStringField;
    qryOrcamentoCIDADE_EMP: TStringField;
    qryOrcamentoFONE_EMP: TStringField;
    qryOrcamentoNOME_VENDEDOR: TStringField;
    qryOrcamentoFORMA_PAGAMENTO: TStringField;
    qryOrcamentoDESCRICAO_PRO: TStringField;
    qryOrcamentoBAIRRO_PRO: TStringField;
    qryOrcamentoCEP_PRO: TStringField;
    qryOrcamentoCIDADE_PRO: TStringField;
    qryOrcamentoFONE_PRO: TStringField;
    qryOrcamentoESTADO_PRO: TStringField;
    qryOrcamentoINSCEST_PRO: TStringField;
    qryOrcamentoCODIGO_CLIENTE: TIntegerField;
    qryOrcamentoNOME_CLIENTE: TStringField;
    qryOrcamentoFANTASIA_CLIENTE: TStringField;
    qryOrcamentoCNPJ_CLIENTE: TStringField;
    qryOrcamentoNOME_CIDADE: TStringField;
    qryOrcamentoCOB_NOME_CIDADE: TStringField;
    qryOrcamentoCOB_ENDERECO_CLIENTE: TStringField;
    qryOrcamentoBANCO1_CLIENTE: TStringField;
    qryOrcamentoENDERECO_CLIENTE: TStringField;
    qryOrcamentoBAIRRO_CLIENTE: TStringField;
    qryOrcamentoCEP_CLIENTE: TStringField;
    qryOrcamentoCIDADE_CLIENTE: TIntegerField;
    qryOrcamentoTELEFONE_CLIENTE: TStringField;
    qryOrcamentoESTADO_CLIENTE: TStringField;
    qryOrcamentoINSCRICAO_CLIENTE: TStringField;
    qryItensOrc: TSQLQuery;
    qryItensOrcID_VENDA_ITEM: TIntegerField;
    qryItensOrcCODIGO_IVENDA: TIntegerField;
    qryItensOrcPRODUTO_IVENDA: TIntegerField;
    qryItensOrcDESCRICAO_IVENDAS: TStringField;
    qryItensOrcVALORBRUTO_IVENDAS: TFMTBCDField;
    qryItensOrcQUANTIDADE_IVENDAS: TFMTBCDField;
    qryItensOrcGRADE_IVENDAS: TStringField;
    qryItensOrcPROMOCAO_IVENDAS: TStringField;
    qryItensOrcFABRICA_IVENDAS: TStringField;
    qryItensOrcSERIE_IVENDAS: TStringField;
    qryItensOrcDESCONTO_IVENDAS: TFMTBCDField;
    qryItensOrcICM_IVENDAS: TFMTBCDField;
    qryItensOrcIPI_IVENDAS: TFMTBCDField;
    qryItensOrcREDUTOR_IVENDAS: TFMTBCDField;
    qryItensOrcTRIBUTACAO_IVENDAS: TStringField;
    qryItensOrcFISCAL_IVENDAS: TStringField;
    qryItensOrcGARANTIA_IVENDAS: TStringField;
    qryItensOrcTECNICO_IVENDAS: TIntegerField;
    qryItensOrcALTURA_IVENDAS: TFMTBCDField;
    qryItensOrcLARGURA_IVENDAS: TFMTBCDField;
    qryItensOrcCOMPRIMENTO_VENDAS: TFMTBCDField;
    qryItensOrcQTDE_VENDAS: TIntegerField;
    qryItensOrcCOMPLEMENTO: TStringField;
    qryItensOrcCOD_EMPRESA: TIntegerField;
    qryItensOrcCLASSE_IVENDA: TStringField;
    qryItensOrcVALORTOTAL: TFMTBCDField;
    qryItensOrcFABRICA_PRODUTO: TIntegerField;
    qryItensOrcFABRICANTE_PRODUTO: TStringField;
    qryItensOrcUNIDADE_PRODUTO: TStringField;
    qryItensOrcCODIGO_GRADE: TStringField;
    qryItensOrcPRECO_CUSTO_PRODUTO: TFMTBCDField;
    dspOrcamento: TDataSetProvider;
    pplOrc: TppDBPipeline;
    pplCliente: TppDBPipeline;
    dsConnectItensOrc: TDataSource;
    rptOrc_01: TppReport;
    ppHeaderBand2: TppHeaderBand;
    ppLabel1: TppLabel;
    ppLine1: TppLine;
    ppLine2: TppLine;
    ppLabel2: TppLabel;
    ppLabel3: TppLabel;
    ppLabel4: TppLabel;
    ppSystemVariable1: TppSystemVariable;
    ppLine3: TppLine;
    ppLabel5: TppLabel;
    ppLabel6: TppLabel;
    ppLabel7: TppLabel;
    ppLabel8: TppLabel;
    ppLabel9: TppLabel;
    ppLabel10: TppLabel;
    ppLine4: TppLine;
    ppLabel11: TppLabel;
    ppLabel12: TppLabel;
    ppLabel13: TppLabel;
    ppLabel14: TppLabel;
    ppLabel15: TppLabel;
    ppLabel16: TppLabel;
    ppLabel17: TppLabel;
    ppLabel18: TppLabel;
    ppLabel19: TppLabel;
    ppLabel20: TppLabel;
    ppDBText1: TppDBText;
    ppDBText2: TppDBText;
    ppDBText3: TppDBText;
    ppDBText4: TppDBText;
    ppDBText5: TppDBText;
    ppDBText6: TppDBText;
    ppDBText38: TppDBText;
    ppDBText39: TppDBText;
    ppDBText40: TppDBText;
    ppDBText41: TppDBText;
    ppDBText42: TppDBText;
    ppDBText43: TppDBText;
    ppDBText44: TppDBText;
    ppLabel48: TppLabel;
    ppDBText45: TppDBText;
    ppLabel55: TppLabel;
    ppDBText46: TppDBText;
    ppLabel67: TppLabel;
    ppDBText63: TppDBText;
    ppLabel68: TppLabel;
    ppLabel69: TppLabel;
    ppLabel70: TppLabel;
    ppLabel71: TppLabel;
    ppLabel72: TppLabel;
    ppLabel73: TppLabel;
    ppDetailBand2: TppDetailBand;
    ppDBText47: TppDBText;
    ppDBText48: TppDBText;
    ppDBText49: TppDBText;
    ppDBText50: TppDBText;
    ppDBText51: TppDBText;
    ppDBText52: TppDBText;
    ppFooterBand2: TppFooterBand;
    ppLabel56: TppLabel;
    ppLabel57: TppLabel;
    ppDBText54: TppDBText;
    ppLabel59: TppLabel;
    ppLabel60: TppLabel;
    ppDBText56: TppDBText;
    ppDBText57: TppDBText;
    ppDBText58: TppDBText;
    ppLabel62: TppLabel;
    ppDBText59: TppDBText;
    ppLabel63: TppLabel;
    ppDBText60: TppDBText;
    ppLabel64: TppLabel;
    ppDBText61: TppDBText;
    ppLabel65: TppLabel;
    ppDBText62: TppDBText;
    ppLabel66: TppLabel;
    ppLine9: TppLine;
    ppLabel61: TppLabel;
    ppLine10: TppLine;
    ppLabel58: TppLabel;
    ppLabel74: TppLabel;
    ppLabel75: TppLabel;
    ppLabel76: TppLabel;
    ppLabel77: TppLabel;
    ppLabel78: TppLabel;
    ppLabel79: TppLabel;
    ppLabel80: TppLabel;
    ppLabel81: TppLabel;
    ppLabel82: TppLabel;
    ppLabel83: TppLabel;
    ppLabel84: TppLabel;
    ppLabel85: TppLabel;
    ppLabel86: TppLabel;
    ppLabel87: TppLabel;
    ppLine11: TppLine;
    ppLabel88: TppLabel;
    ppLabel89: TppLabel;
    ppLabel90: TppLabel;
    ppLabel91: TppLabel;
    raCodeModule1: TraCodeModule;
    ppParameterList1: TppParameterList;
    rptOrc_02: TppReport;
    ppHeaderBand3: TppHeaderBand;
    ppLabel92: TppLabel;
    ppLine12: TppLine;
    ppLine13: TppLine;
    ppLabel93: TppLabel;
    ppLabel94: TppLabel;
    ppLabel95: TppLabel;
    ppSystemVariable3: TppSystemVariable;
    ppLine14: TppLine;
    ppLabel96: TppLabel;
    ppLabel97: TppLabel;
    ppLabel98: TppLabel;
    ppLabel99: TppLabel;
    ppLabel100: TppLabel;
    ppLabel101: TppLabel;
    ppLine15: TppLine;
    ppLabel102: TppLabel;
    ppLabel103: TppLabel;
    ppLabel104: TppLabel;
    ppLabel105: TppLabel;
    ppLabel106: TppLabel;
    ppLabel107: TppLabel;
    ppLabel108: TppLabel;
    ppLabel109: TppLabel;
    ppLabel110: TppLabel;
    ppLabel111: TppLabel;
    ppDBText53: TppDBText;
    ppDBText55: TppDBText;
    ppDBText64: TppDBText;
    ppDBText65: TppDBText;
    ppDBText66: TppDBText;
    ppDBText67: TppDBText;
    ppDBText68: TppDBText;
    ppDBText69: TppDBText;
    ppDBText70: TppDBText;
    ppDBText71: TppDBText;
    ppDBText72: TppDBText;
    ppDBText73: TppDBText;
    ppDBText74: TppDBText;
    ppLabel112: TppLabel;
    ppDBText75: TppDBText;
    ppLabel113: TppLabel;
    ppDBText76: TppDBText;
    ppLabel114: TppLabel;
    ppDBText77: TppDBText;
    ppLabel115: TppLabel;
    ppLabel116: TppLabel;
    ppLabel117: TppLabel;
    ppLabel118: TppLabel;
    ppLabel119: TppLabel;
    ppLabel120: TppLabel;
    ppLabel453: TppLabel;
    ppLabel454: TppLabel;
    ppDetailBand3: TppDetailBand;
    ppDBText78: TppDBText;
    ppDBText79: TppDBText;
    ppDBText80: TppDBText;
    ppDBText81: TppDBText;
    ppDBText82: TppDBText;
    ppDBText83: TppDBText;
    ppDBText267: TppDBText;
    ppDBText268: TppDBText;
    ppFooterBand3: TppFooterBand;
    ppLabel121: TppLabel;
    ppLabel122: TppLabel;
    ppDBText84: TppDBText;
    ppLabel123: TppLabel;
    ppLabel124: TppLabel;
    ppDBText85: TppDBText;
    ppDBText86: TppDBText;
    ppDBText87: TppDBText;
    ppLabel125: TppLabel;
    ppDBText88: TppDBText;
    ppLabel126: TppLabel;
    ppDBText89: TppDBText;
    ppLabel127: TppLabel;
    ppDBText90: TppDBText;
    ppLabel128: TppLabel;
    ppDBText91: TppDBText;
    ppLabel129: TppLabel;
    ppLine16: TppLine;
    ppLabel130: TppLabel;
    ppLine17: TppLine;
    ppLabel131: TppLabel;
    ppLabel132: TppLabel;
    ppLabel133: TppLabel;
    ppLabel134: TppLabel;
    ppLabel135: TppLabel;
    ppLabel136: TppLabel;
    ppLabel137: TppLabel;
    ppLabel138: TppLabel;
    ppLabel139: TppLabel;
    ppLabel140: TppLabel;
    ppLabel141: TppLabel;
    ppLabel142: TppLabel;
    ppLabel143: TppLabel;
    ppLabel144: TppLabel;
    ppLabel145: TppLabel;
    ppLine18: TppLine;
    ppLabel146: TppLabel;
    ppLabel147: TppLabel;
    ppLabel148: TppLabel;
    ppLabel149: TppLabel;
    raCodeModule3: TraCodeModule;
    ppParameterList3: TppParameterList;
    rptORc_03: TppReport;
    ppHeaderBand4: TppHeaderBand;
    ppLabel150: TppLabel;
    ppLine19: TppLine;
    ppLine20: TppLine;
    ppLabel151: TppLabel;
    ppLabel152: TppLabel;
    ppLabel153: TppLabel;
    ppSystemVariable4: TppSystemVariable;
    ppLine21: TppLine;
    ppLabel154: TppLabel;
    ppLabel155: TppLabel;
    ppLabel156: TppLabel;
    ppLabel157: TppLabel;
    ppLabel158: TppLabel;
    ppLabel159: TppLabel;
    ppLine22: TppLine;
    ppLabel160: TppLabel;
    ppLabel161: TppLabel;
    ppLabel162: TppLabel;
    ppLabel163: TppLabel;
    ppLabel164: TppLabel;
    ppLabel165: TppLabel;
    ppLabel166: TppLabel;
    ppLabel167: TppLabel;
    ppLabel168: TppLabel;
    ppLabel169: TppLabel;
    ppDBText92: TppDBText;
    ppDBText93: TppDBText;
    ppDBText94: TppDBText;
    ppDBText95: TppDBText;
    ppDBText96: TppDBText;
    ppDBText97: TppDBText;
    ppDBText98: TppDBText;
    ppDBText99: TppDBText;
    ppDBText100: TppDBText;
    ppDBText101: TppDBText;
    ppDBText102: TppDBText;
    ppDBText103: TppDBText;
    ppDBText104: TppDBText;
    ppLabel170: TppLabel;
    ppDBText105: TppDBText;
    ppLabel171: TppLabel;
    ppDBText106: TppDBText;
    ppDetailBand4: TppDetailBand;
    ppDBText107: TppDBText;
    ppDBText108: TppDBText;
    ppDBText109: TppDBText;
    ppDBText110: TppDBText;
    ppDBText111: TppDBText;
    ppDBText112: TppDBText;
    ppFooterBand4: TppFooterBand;
    ppLabel173: TppLabel;
    ppDBText114: TppDBText;
    ppLabel174: TppLabel;
    ppDBText115: TppDBText;
    ppLabel175: TppLabel;
    ppLabel176: TppLabel;
    ppLabel177: TppLabel;
    ppDBText116: TppDBText;
    ppDBText117: TppDBText;
    ppDBText118: TppDBText;
    ppLabel178: TppLabel;
    ppDBText119: TppDBText;
    ppLabel179: TppLabel;
    ppDBText120: TppDBText;
    ppLabel180: TppLabel;
    ppDBText121: TppDBText;
    ppLabel181: TppLabel;
    ppDBText122: TppDBText;
    ppLabel182: TppLabel;
    ppLabel172: TppLabel;
    ppLabel183: TppLabel;
    ppLabel184: TppLabel;
    ppLabel185: TppLabel;
    ppLabel186: TppLabel;
    ppLabel187: TppLabel;
    ppLabel188: TppLabel;
    ppLabel189: TppLabel;
    ppLabel190: TppLabel;
    ppLabel191: TppLabel;
    ppLabel192: TppLabel;
    ppLabel193: TppLabel;
    ppLabel194: TppLabel;
    ppLabel195: TppLabel;
    ppLabel196: TppLabel;
    ppLabel197: TppLabel;
    raCodeModule4: TraCodeModule;
    ppParameterList4: TppParameterList;
    rptOrc_05: TppReport;
    ppHeaderBand5: TppHeaderBand;
    ppLabel198: TppLabel;
    ppLine23: TppLine;
    ppLine24: TppLine;
    ppLabel199: TppLabel;
    ppLabel200: TppLabel;
    ppLabel201: TppLabel;
    ppSystemVariable5: TppSystemVariable;
    ppLine25: TppLine;
    ppLabel202: TppLabel;
    ppLabel203: TppLabel;
    ppLabel204: TppLabel;
    ppLabel205: TppLabel;
    ppLabel206: TppLabel;
    ppLabel207: TppLabel;
    ppLine26: TppLine;
    ppLabel208: TppLabel;
    ppLabel209: TppLabel;
    ppLabel210: TppLabel;
    ppLabel211: TppLabel;
    ppLabel212: TppLabel;
    ppLabel213: TppLabel;
    ppLabel214: TppLabel;
    ppLabel215: TppLabel;
    ppLabel216: TppLabel;
    ppLabel217: TppLabel;
    ppDBText113: TppDBText;
    ppDBText123: TppDBText;
    ppDBText124: TppDBText;
    ppDBText125: TppDBText;
    ppDBText126: TppDBText;
    ppDBText127: TppDBText;
    ppDBText128: TppDBText;
    ppDBText129: TppDBText;
    ppDBText130: TppDBText;
    ppDBText131: TppDBText;
    ppDBText132: TppDBText;
    ppDBText133: TppDBText;
    ppDBText134: TppDBText;
    ppLabel218: TppLabel;
    ppDBText135: TppDBText;
    ppLabel219: TppLabel;
    ppDBText136: TppDBText;
    ppLabel220: TppLabel;
    ppDBText137: TppDBText;
    ppLabel221: TppLabel;
    ppLabel222: TppLabel;
    ppLabel223: TppLabel;
    ppLabel224: TppLabel;
    ppLabel225: TppLabel;
    ppLabel226: TppLabel;
    ppLabel322: TppLabel;
    ppDetailBand5: TppDetailBand;
    ppDBText138: TppDBText;
    ppDBText139: TppDBText;
    ppDBText140: TppDBText;
    ppDBText141: TppDBText;
    ppDBText142: TppDBText;
    ppDBText143: TppDBText;
    ppDBText192: TppDBText;
    ppFooterBand5: TppFooterBand;
    ppLabel227: TppLabel;
    ppLabel228: TppLabel;
    ppDBText144: TppDBText;
    ppLabel229: TppLabel;
    ppLabel230: TppLabel;
    ppDBText145: TppDBText;
    ppDBText146: TppDBText;
    ppDBText147: TppDBText;
    ppLabel231: TppLabel;
    ppDBText148: TppDBText;
    ppLabel232: TppLabel;
    ppDBText149: TppDBText;
    ppLabel233: TppLabel;
    ppDBText150: TppDBText;
    ppLabel234: TppLabel;
    ppDBText151: TppDBText;
    ppLabel235: TppLabel;
    ppLine27: TppLine;
    ppLabel236: TppLabel;
    ppLine28: TppLine;
    ppLabel237: TppLabel;
    ppLabel238: TppLabel;
    ppLabel239: TppLabel;
    ppLabel240: TppLabel;
    ppLabel241: TppLabel;
    ppLabel242: TppLabel;
    ppLabel243: TppLabel;
    ppLabel244: TppLabel;
    ppLabel245: TppLabel;
    ppLabel246: TppLabel;
    ppLabel247: TppLabel;
    ppLabel248: TppLabel;
    ppLabel249: TppLabel;
    ppLabel250: TppLabel;
    ppLabel251: TppLabel;
    ppLabel256: TppLabel;
    ppDBText152: TppDBText;
    raCodeModule5: TraCodeModule;
    ppParameterList5: TppParameterList;
    rptOrc_07: TppReport;
    ppHeaderBand6: TppHeaderBand;
    ppLabel252: TppLabel;
    ppLine29: TppLine;
    ppLine30: TppLine;
    ppLabel253: TppLabel;
    ppLabel254: TppLabel;
    ppLabel255: TppLabel;
    ppSystemVariable6: TppSystemVariable;
    ppLine31: TppLine;
    ppLabel257: TppLabel;
    ppLabel258: TppLabel;
    ppLabel259: TppLabel;
    ppLabel260: TppLabel;
    ppLabel261: TppLabel;
    ppLabel262: TppLabel;
    ppLine32: TppLine;
    ppLabel263: TppLabel;
    ppLabel264: TppLabel;
    ppLabel265: TppLabel;
    ppLabel266: TppLabel;
    ppLabel267: TppLabel;
    ppLabel268: TppLabel;
    ppLabel269: TppLabel;
    ppLabel270: TppLabel;
    ppLabel271: TppLabel;
    ppLabel272: TppLabel;
    ppDBText153: TppDBText;
    ppDBText154: TppDBText;
    ppDBText155: TppDBText;
    ppDBText156: TppDBText;
    ppDBText157: TppDBText;
    ppDBText158: TppDBText;
    ppDBText159: TppDBText;
    ppDBText160: TppDBText;
    ppDBText161: TppDBText;
    ppDBText162: TppDBText;
    ppDBText163: TppDBText;
    ppDBText164: TppDBText;
    ppDBText165: TppDBText;
    ppLabel273: TppLabel;
    ppDBText166: TppDBText;
    ppLabel274: TppLabel;
    ppDBText167: TppDBText;
    ppLabel275: TppLabel;
    ppDBText168: TppDBText;
    ppLabel276: TppLabel;
    ppLabel277: TppLabel;
    ppLabel278: TppLabel;
    ppLabel279: TppLabel;
    ppLabel280: TppLabel;
    ppLabel281: TppLabel;
    ppDetailBand6: TppDetailBand;
    ppDBText169: TppDBText;
    ppDBText170: TppDBText;
    ppDBText171: TppDBText;
    ppDBText172: TppDBText;
    ppDBText173: TppDBText;
    ppDBText174: TppDBText;
    ppFooterBand6: TppFooterBand;
    ppLabel282: TppLabel;
    ppLabel283: TppLabel;
    ppDBText175: TppDBText;
    ppLabel284: TppLabel;
    ppLabel285: TppLabel;
    ppDBText176: TppDBText;
    ppDBText177: TppDBText;
    ppDBText178: TppDBText;
    ppLabel286: TppLabel;
    ppDBText179: TppDBText;
    ppLabel287: TppLabel;
    ppDBText180: TppDBText;
    ppLabel288: TppLabel;
    ppDBText181: TppDBText;
    ppLabel289: TppLabel;
    ppDBText182: TppDBText;
    ppLabel290: TppLabel;
    ppLine33: TppLine;
    ppLabel291: TppLabel;
    ppLine34: TppLine;
    ppLabel292: TppLabel;
    ppLabel296: TppLabel;
    ppLabel297: TppLabel;
    ppLabel300: TppLabel;
    ppLabel301: TppLabel;
    ppLabel294: TppLabel;
    ppLabel295: TppLabel;
    ppDBText183: TppDBText;
    raCodeModule6: TraCodeModule;
    ppParameterList6: TppParameterList;
    rptOrc_06: TppReport;
    ppHeaderBand8: TppHeaderBand;
    ppLabel325: TppLabel;
    ppLine40: TppLine;
    ppLine41: TppLine;
    ppLabel327: TppLabel;
    ppLabel328: TppLabel;
    ppLabel329: TppLabel;
    ppSystemVariable7: TppSystemVariable;
    ppLine42: TppLine;
    ppLabel330: TppLabel;
    ppLabel331: TppLabel;
    ppLabel342: TppLabel;
    ppLabel343: TppLabel;
    ppLabel344: TppLabel;
    ppLabel345: TppLabel;
    ppLine43: TppLine;
    ppLabel346: TppLabel;
    ppLabel347: TppLabel;
    ppLabel348: TppLabel;
    ppLabel349: TppLabel;
    ppLabel350: TppLabel;
    ppLabel351: TppLabel;
    ppLabel352: TppLabel;
    ppLabel353: TppLabel;
    ppLabel354: TppLabel;
    ppLabel355: TppLabel;
    ppDBText193: TppDBText;
    ppDBText196: TppDBText;
    ppDBText205: TppDBText;
    ppDBText206: TppDBText;
    ppDBText209: TppDBText;
    ppDBText211: TppDBText;
    ppDBText212: TppDBText;
    ppDBText213: TppDBText;
    ppDBText214: TppDBText;
    ppDBText215: TppDBText;
    ppDBText216: TppDBText;
    ppDBText217: TppDBText;
    ppDBText218: TppDBText;
    ppLabel356: TppLabel;
    ppDBText219: TppDBText;
    ppLabel357: TppLabel;
    ppDBText220: TppDBText;
    ppLabel358: TppLabel;
    ppDBText221: TppDBText;
    ppLabel359: TppLabel;
    ppLabel360: TppLabel;
    ppLabel361: TppLabel;
    ppLabel362: TppLabel;
    ppLabel363: TppLabel;
    ppLabel364: TppLabel;
    ppLabel394: TppLabel;
    ppDetailBand8: TppDetailBand;
    ppDBText222: TppDBText;
    ppDBText223: TppDBText;
    ppDBText224: TppDBText;
    ppDBText225: TppDBText;
    ppDBText226: TppDBText;
    ppDBText227: TppDBText;
    ppDBText236: TppDBText;
    ppFooterBand8: TppFooterBand;
    ppLabel365: TppLabel;
    ppLabel366: TppLabel;
    ppDBText228: TppDBText;
    ppLabel367: TppLabel;
    ppLabel368: TppLabel;
    ppDBText229: TppDBText;
    ppDBText230: TppDBText;
    ppDBText231: TppDBText;
    ppLabel369: TppLabel;
    ppDBText232: TppDBText;
    ppLabel370: TppLabel;
    ppDBText233: TppDBText;
    ppLabel371: TppLabel;
    ppDBText234: TppDBText;
    ppLabel372: TppLabel;
    ppDBText235: TppDBText;
    ppLabel373: TppLabel;
    ppLine44: TppLine;
    ppLabel374: TppLabel;
    ppLine45: TppLine;
    ppLabel375: TppLabel;
    ppLabel376: TppLabel;
    ppLabel377: TppLabel;
    ppLabel378: TppLabel;
    ppLabel379: TppLabel;
    ppLabel380: TppLabel;
    ppLabel381: TppLabel;
    ppLabel382: TppLabel;
    ppLabel383: TppLabel;
    ppLabel384: TppLabel;
    ppLabel385: TppLabel;
    ppLabel386: TppLabel;
    ppLabel387: TppLabel;
    ppLabel388: TppLabel;
    ppLabel389: TppLabel;
    ppLine46: TppLine;
    ppLabel390: TppLabel;
    ppLabel391: TppLabel;
    ppLabel392: TppLabel;
    ppLabel393: TppLabel;
    raCodeModule8: TraCodeModule;
    ppParameterList8: TppParameterList;
    rptOrc_04: TppReport;
    ppHeaderBand9: TppHeaderBand;
    ppLabel395: TppLabel;
    ppLine47: TppLine;
    ppLine48: TppLine;
    ppLabel396: TppLabel;
    ppLabel397: TppLabel;
    ppLabel398: TppLabel;
    ppSystemVariable8: TppSystemVariable;
    ppLine49: TppLine;
    ppLabel399: TppLabel;
    ppLabel400: TppLabel;
    ppLabel401: TppLabel;
    ppLabel402: TppLabel;
    ppLabel403: TppLabel;
    ppLabel404: TppLabel;
    ppLine50: TppLine;
    ppLabel405: TppLabel;
    ppLabel406: TppLabel;
    ppLabel407: TppLabel;
    ppLabel408: TppLabel;
    ppLabel409: TppLabel;
    ppLabel410: TppLabel;
    ppLabel411: TppLabel;
    ppLabel412: TppLabel;
    ppLabel413: TppLabel;
    ppLabel414: TppLabel;
    ppDBText237: TppDBText;
    ppDBText238: TppDBText;
    ppDBText239: TppDBText;
    ppDBText240: TppDBText;
    ppDBText241: TppDBText;
    ppDBText242: TppDBText;
    ppDBText243: TppDBText;
    ppDBText244: TppDBText;
    ppDBText245: TppDBText;
    ppDBText246: TppDBText;
    ppDBText247: TppDBText;
    ppDBText248: TppDBText;
    ppDBText249: TppDBText;
    ppLabel415: TppLabel;
    ppDBText250: TppDBText;
    ppLabel416: TppLabel;
    ppDBText251: TppDBText;
    ppLabel417: TppLabel;
    ppDBText252: TppDBText;
    ppLabel418: TppLabel;
    ppLabel419: TppLabel;
    ppLabel420: TppLabel;
    ppLabel421: TppLabel;
    ppLabel422: TppLabel;
    ppLabel423: TppLabel;
    ppDetailBand9: TppDetailBand;
    ppDBText253: TppDBText;
    ppDBText254: TppDBText;
    ppDBText255: TppDBText;
    ppDBText256: TppDBText;
    ppDBText257: TppDBText;
    ppDBText258: TppDBText;
    ppFooterBand9: TppFooterBand;
    ppLabel424: TppLabel;
    ppLabel425: TppLabel;
    ppDBText259: TppDBText;
    ppLabel426: TppLabel;
    ppLabel427: TppLabel;
    ppDBText260: TppDBText;
    ppDBText261: TppDBText;
    ppDBText262: TppDBText;
    ppLabel428: TppLabel;
    ppDBText263: TppDBText;
    ppLabel429: TppLabel;
    ppDBText264: TppDBText;
    ppLabel430: TppLabel;
    ppDBText265: TppDBText;
    ppLabel431: TppLabel;
    ppDBText266: TppDBText;
    ppLabel432: TppLabel;
    ppLine51: TppLine;
    ppLabel433: TppLabel;
    ppLine52: TppLine;
    ppLabel434: TppLabel;
    ppLabel435: TppLabel;
    ppLabel436: TppLabel;
    ppLabel437: TppLabel;
    ppLabel438: TppLabel;
    ppLabel439: TppLabel;
    ppLabel440: TppLabel;
    ppLabel441: TppLabel;
    ppLabel442: TppLabel;
    ppLabel443: TppLabel;
    ppLabel444: TppLabel;
    ppLabel445: TppLabel;
    ppLabel446: TppLabel;
    ppLabel447: TppLabel;
    ppLabel448: TppLabel;
    ppLine53: TppLine;
    ppLabel449: TppLabel;
    ppLabel450: TppLabel;
    ppLabel451: TppLabel;
    ppLabel452: TppLabel;
    raCodeModule9: TraCodeModule;
    ppParameterList9: TppParameterList;
    rptOrc_09: TppReport;
    ppHeaderBand10: TppHeaderBand;
    ppLabel455: TppLabel;
    ppLine54: TppLine;
    ppLine55: TppLine;
    ppLabel456: TppLabel;
    ppLabel457: TppLabel;
    ppLabel458: TppLabel;
    ppSystemVariable9: TppSystemVariable;
    ppLine56: TppLine;
    ppLabel459: TppLabel;
    ppLabel460: TppLabel;
    ppLabel461: TppLabel;
    ppLabel462: TppLabel;
    ppLabel463: TppLabel;
    ppLabel464: TppLabel;
    ppLine57: TppLine;
    ppLabel466: TppLabel;
    ppLabel468: TppLabel;
    ppLabel469: TppLabel;
    ppLabel470: TppLabel;
    ppLabel471: TppLabel;
    ppLabel472: TppLabel;
    ppLabel473: TppLabel;
    ppLabel474: TppLabel;
    ppDBText269: TppDBText;
    ppDBText270: TppDBText;
    ppDBText271: TppDBText;
    ppDBText272: TppDBText;
    ppDBText274: TppDBText;
    ppDBText275: TppDBText;
    ppDBText276: TppDBText;
    ppDBText277: TppDBText;
    ppDBText278: TppDBText;
    ppDBText280: TppDBText;
    ppDBText281: TppDBText;
    ppLabel475: TppLabel;
    ppDBText282: TppDBText;
    ppDBText283: TppDBText;
    ppLabel476: TppLabel;
    ppLabel465: TppLabel;
    ppDBText273: TppDBText;
    ppDetailBand10: TppDetailBand;
    ppDBText284: TppDBText;
    ppDBText285: TppDBText;
    ppDBText286: TppDBText;
    ppDBText287: TppDBText;
    ppDBText288: TppDBText;
    ppDBText289: TppDBText;
    ppFooterBand10: TppFooterBand;
    ppLabel477: TppLabel;
    ppDBText290: TppDBText;
    ppLabel478: TppLabel;
    ppDBText291: TppDBText;
    ppLabel479: TppLabel;
    ppLabel480: TppLabel;
    ppLabel481: TppLabel;
    ppDBText292: TppDBText;
    ppDBText293: TppDBText;
    ppDBText294: TppDBText;
    ppLabel482: TppLabel;
    ppDBText295: TppDBText;
    ppDBText296: TppDBText;
    ppDBText297: TppDBText;
    ppDBText298: TppDBText;
    ppLabel487: TppLabel;
    ppLabel488: TppLabel;
    ppLabel489: TppLabel;
    ppLabel490: TppLabel;
    ppLabel491: TppLabel;
    ppLabel492: TppLabel;
    ppLabel493: TppLabel;
    ppLabel494: TppLabel;
    ppLabel495: TppLabel;
    ppLabel496: TppLabel;
    ppLabel497: TppLabel;
    ppLabel498: TppLabel;
    ppLabel499: TppLabel;
    ppLabel500: TppLabel;
    ppLabel501: TppLabel;
    ppLabel502: TppLabel;
    ppLine58: TppLine;
    ppLine59: TppLine;
    ppLine60: TppLine;
    ppDBText279: TppDBText;
    ppLine61: TppLine;
    raCodeModule10: TraCodeModule;
    ppParameterList10: TppParameterList;
    rptOrc_A: TppReport;
    ppHeaderBand11: TppHeaderBand;
    ppLine62: TppLine;
    ppLine63: TppLine;
    ppLabel504: TppLabel;
    ppLabel505: TppLabel;
    ppLabel506: TppLabel;
    ppLabel507: TppLabel;
    ppLine65: TppLine;
    ppLabel508: TppLabel;
    ppLabel509: TppLabel;
    ppLabel510: TppLabel;
    ppLabel511: TppLabel;
    ppLabel512: TppLabel;
    ppLabel513: TppLabel;
    ppLabel514: TppLabel;
    ppLabel515: TppLabel;
    ppDBText300: TppDBText;
    ppDBText301: TppDBText;
    ppDBText302: TppDBText;
    ppDBText303: TppDBText;
    ppDBText304: TppDBText;
    ppDBText308: TppDBText;
    ppDBText309: TppDBText;
    ppLabel516: TppLabel;
    ppLabel518: TppLabel;
    ppDBText312: TppDBText;
    ppLabel467: TppLabel;
    ppLabel483: TppLabel;
    ppLabel484: TppLabel;
    ppLabel485: TppLabel;
    ppSystemVariable10: TppSystemVariable;
    ppLine64: TppLine;
    ppLabel486: TppLabel;
    ppLabel503: TppLabel;
    ppDBText299: TppDBText;
    ppDBText305: TppDBText;
    ppDBText306: TppDBText;
    ppDBText307: TppDBText;
    ppDBText310: TppDBText;
    ppLabel517: TppLabel;
    ppDBText311: TppDBText;
    ppDetailBand11: TppDetailBand;
    ppDBText313: TppDBText;
    ppDBText314: TppDBText;
    ppDBText315: TppDBText;
    ppDBText316: TppDBText;
    ppDBText317: TppDBText;
    ppDBText318: TppDBText;
    ppFooterBand11: TppFooterBand;
    ppLabel519: TppLabel;
    ppDBText319: TppDBText;
    ppLabel520: TppLabel;
    ppDBText320: TppDBText;
    ppLabel521: TppLabel;
    ppLabel522: TppLabel;
    ppLabel523: TppLabel;
    ppDBText321: TppDBText;
    ppDBText322: TppDBText;
    ppDBText323: TppDBText;
    ppLabel524: TppLabel;
    ppDBText324: TppDBText;
    ppDBText325: TppDBText;
    ppDBText326: TppDBText;
    ppDBText327: TppDBText;
    ppLabel525: TppLabel;
    ppLine66: TppLine;
    ppLine67: TppLine;
    ppLine68: TppLine;
    ppDBText328: TppDBText;
    ppLine69: TppLine;
    ppDBText329: TppDBText;
    raCodeModule11: TraCodeModule;
    ppParameterList11: TppParameterList;
    rptOrc_08: TppReport;
    ppHeaderBand12: TppHeaderBand;
    ppLine70: TppLine;
    ppLabel526: TppLabel;
    ppLine71: TppLine;
    ppLabel527: TppLabel;
    ppLabel528: TppLabel;
    ppLabel529: TppLabel;
    ppLine72: TppLine;
    ppLabel530: TppLabel;
    ppLabel531: TppLabel;
    ppLabel532: TppLabel;
    ppLabel533: TppLabel;
    ppLabel534: TppLabel;
    ppLabel535: TppLabel;
    ppLabel536: TppLabel;
    ppLabel537: TppLabel;
    ppLabel538: TppLabel;
    ppLabel539: TppLabel;
    ppDBText330: TppDBText;
    ppDBText331: TppDBText;
    ppDBText332: TppDBText;
    ppDBText333: TppDBText;
    ppDBText334: TppDBText;
    ppDBText335: TppDBText;
    ppDBText336: TppDBText;
    ppDBText337: TppDBText;
    ppDBText338: TppDBText;
    ppDBText339: TppDBText;
    ppLine73: TppLine;
    ppLabel540: TppLabel;
    ppDetailBand12: TppDetailBand;
    ppDBText340: TppDBText;
    ppDBText341: TppDBText;
    ppDBText342: TppDBText;
    ppDBText343: TppDBText;
    ppDBText344: TppDBText;
    ppDBText345: TppDBText;
    ppDBText346: TppDBText;
    ppFooterBand12: TppFooterBand;
    ppLabel541: TppLabel;
    ppDBText347: TppDBText;
    ppLabel542: TppLabel;
    ppLabel543: TppLabel;
    ppDBText348: TppDBText;
    ppDBText349: TppDBText;
    ppLabel544: TppLabel;
    ppDBText350: TppDBText;
    ppLabel545: TppLabel;
    ppLabel546: TppLabel;
    ppLine74: TppLine;
    ppLabel547: TppLabel;
    ppLabel548: TppLabel;
    ppLabel549: TppLabel;
    ppLabel550: TppLabel;
    ppLabel551: TppLabel;
    ppLabel552: TppLabel;
    ppLabel553: TppLabel;
    ppLabel554: TppLabel;
    ppLabel555: TppLabel;
    ppLabel556: TppLabel;
    ppLabel557: TppLabel;
    ppLabel558: TppLabel;
    ppLabel559: TppLabel;
    ppLabel560: TppLabel;
    ppLabel561: TppLabel;
    raCodeModule12: TraCodeModule;
    ppParameterList12: TppParameterList;
    rptOrc_C: TppReport;
    ppHeaderBand7: TppHeaderBand;
    ppLabel293: TppLabel;
    ppLine35: TppLine;
    ppLine36: TppLine;
    ppLabel298: TppLabel;
    ppLabel299: TppLabel;
    ppLabel302: TppLabel;
    ppSystemVariable11: TppSystemVariable;
    ppLine37: TppLine;
    ppLabel303: TppLabel;
    ppLabel304: TppLabel;
    ppLabel305: TppLabel;
    ppLabel306: TppLabel;
    ppLabel307: TppLabel;
    ppLabel308: TppLabel;
    ppLine38: TppLine;
    ppLabel309: TppLabel;
    ppLabel310: TppLabel;
    ppLabel311: TppLabel;
    ppLabel312: TppLabel;
    ppLabel313: TppLabel;
    ppLabel314: TppLabel;
    ppLabel315: TppLabel;
    ppLabel316: TppLabel;
    ppLabel317: TppLabel;
    ppLabel318: TppLabel;
    ppDBText184: TppDBText;
    ppDBText185: TppDBText;
    ppDBText186: TppDBText;
    ppDBText187: TppDBText;
    ppDBText188: TppDBText;
    ppDBText189: TppDBText;
    ppDBText190: TppDBText;
    ppDBText191: TppDBText;
    ppDBText194: TppDBText;
    ppDBText195: TppDBText;
    ppDBText197: TppDBText;
    ppDBText198: TppDBText;
    ppDBText199: TppDBText;
    ppLabel319: TppLabel;
    ppDBText200: TppDBText;
    ppLabel320: TppLabel;
    ppDBText201: TppDBText;
    ppLabel321: TppLabel;
    ppDBText202: TppDBText;
    ppLabel323: TppLabel;
    ppLabel324: TppLabel;
    ppLabel326: TppLabel;
    ppLabel332: TppLabel;
    ppLabel333: TppLabel;
    ppLabel334: TppLabel;
    ppLabel584: TppLabel;
    ppLabel585: TppLabel;
    ppDetailBand7: TppDetailBand;
    ppDBText203: TppDBText;
    ppDBText204: TppDBText;
    ppDBText207: TppDBText;
    ppDBText208: TppDBText;
    ppDBText210: TppDBText;
    ppDBText351: TppDBText;
    ppDBText360: TppDBText;
    ppDBText361: TppDBText;
    ppFooterBand7: TppFooterBand;
    ppLabel335: TppLabel;
    ppLabel336: TppLabel;
    ppDBText352: TppDBText;
    ppLabel337: TppLabel;
    ppLabel338: TppLabel;
    ppDBText353: TppDBText;
    ppDBText354: TppDBText;
    ppDBText355: TppDBText;
    ppLabel339: TppLabel;
    ppDBText356: TppDBText;
    ppLabel340: TppLabel;
    ppDBText357: TppDBText;
    ppLabel341: TppLabel;
    ppDBText358: TppDBText;
    ppLabel562: TppLabel;
    ppDBText359: TppDBText;
    ppLabel563: TppLabel;
    ppLine39: TppLine;
    ppLabel564: TppLabel;
    ppLine75: TppLine;
    ppLabel565: TppLabel;
    ppLabel566: TppLabel;
    ppLabel567: TppLabel;
    ppLabel568: TppLabel;
    ppLabel569: TppLabel;
    ppLabel570: TppLabel;
    ppLabel571: TppLabel;
    ppLabel572: TppLabel;
    ppLabel573: TppLabel;
    ppLabel574: TppLabel;
    ppLabel575: TppLabel;
    ppLabel576: TppLabel;
    ppLabel577: TppLabel;
    ppLabel578: TppLabel;
    ppLabel579: TppLabel;
    ppLine76: TppLine;
    ppLabel580: TppLabel;
    ppLabel581: TppLabel;
    ppLabel582: TppLabel;
    ppLabel583: TppLabel;
    raCodeModule7: TraCodeModule;
    ppParameterList7: TppParameterList;
    rptOrc_D: TppReport;
    ppHeaderBand13: TppHeaderBand;
    ppLabel586: TppLabel;
    ppLine77: TppLine;
    ppLine78: TppLine;
    ppLabel587: TppLabel;
    ppLabel588: TppLabel;
    ppLabel589: TppLabel;
    ppSystemVariable12: TppSystemVariable;
    ppLine79: TppLine;
    ppLabel590: TppLabel;
    ppLabel591: TppLabel;
    ppLabel592: TppLabel;
    ppLabel593: TppLabel;
    ppLabel594: TppLabel;
    ppLabel595: TppLabel;
    ppLine80: TppLine;
    ppLabel596: TppLabel;
    ppLabel597: TppLabel;
    ppLabel598: TppLabel;
    ppLabel599: TppLabel;
    ppLabel600: TppLabel;
    ppLabel601: TppLabel;
    ppLabel602: TppLabel;
    ppLabel603: TppLabel;
    ppLabel604: TppLabel;
    ppLabel605: TppLabel;
    ppDBText362: TppDBText;
    ppDBText363: TppDBText;
    ppDBText364: TppDBText;
    ppDBText365: TppDBText;
    ppDBText366: TppDBText;
    ppDBText367: TppDBText;
    ppDBText368: TppDBText;
    ppDBText369: TppDBText;
    ppDBText370: TppDBText;
    ppDBText371: TppDBText;
    ppDBText372: TppDBText;
    ppDBText373: TppDBText;
    ppDBText374: TppDBText;
    ppLabel606: TppLabel;
    ppDBText375: TppDBText;
    ppLabel607: TppLabel;
    ppDBText376: TppDBText;
    ppLabel608: TppLabel;
    ppDBText377: TppDBText;
    ppLabel609: TppLabel;
    ppLabel610: TppLabel;
    ppLabel611: TppLabel;
    ppLabel612: TppLabel;
    ppLabel613: TppLabel;
    ppLabel614: TppLabel;
    ppLabel615: TppLabel;
    ppDetailBand13: TppDetailBand;
    ppDBText378: TppDBText;
    ppDBText379: TppDBText;
    ppDBText380: TppDBText;
    ppDBText381: TppDBText;
    ppDBText382: TppDBText;
    ppDBText383: TppDBText;
    ppDBText384: TppDBText;
    ppFooterBand13: TppFooterBand;
    ppLabel616: TppLabel;
    ppLabel617: TppLabel;
    ppDBText385: TppDBText;
    ppLabel618: TppLabel;
    ppLabel619: TppLabel;
    ppDBText386: TppDBText;
    ppDBText387: TppDBText;
    ppDBText388: TppDBText;
    ppLabel620: TppLabel;
    ppDBText389: TppDBText;
    ppLabel621: TppLabel;
    ppDBText390: TppDBText;
    ppLabel622: TppLabel;
    ppDBText391: TppDBText;
    ppLabel623: TppLabel;
    ppDBText392: TppDBText;
    ppLabel624: TppLabel;
    ppLine81: TppLine;
    ppLabel625: TppLabel;
    ppLine82: TppLine;
    ppLabel626: TppLabel;
    ppLabel627: TppLabel;
    ppLabel628: TppLabel;
    ppLabel629: TppLabel;
    ppLabel630: TppLabel;
    ppLabel631: TppLabel;
    ppLabel632: TppLabel;
    ppLabel633: TppLabel;
    ppLabel634: TppLabel;
    ppLabel635: TppLabel;
    ppLabel636: TppLabel;
    ppLabel637: TppLabel;
    ppLabel638: TppLabel;
    ppLabel639: TppLabel;
    ppLabel640: TppLabel;
    ppLabel641: TppLabel;
    ppDBText393: TppDBText;
    ppLine83: TppLine;
    ppLine84: TppLine;
    ppLine85: TppLine;
    ppDBText394: TppDBText;
    raCodeModule13: TraCodeModule;
    ppParameterList13: TppParameterList;
    rptOrc_E: TppReport;
    ppHeaderBand14: TppHeaderBand;
    ppLabel642: TppLabel;
    ppLine86: TppLine;
    ppLine87: TppLine;
    ppLabel643: TppLabel;
    ppLabel644: TppLabel;
    ppLabel645: TppLabel;
    ppSystemVariable13: TppSystemVariable;
    ppLine88: TppLine;
    ppLabel646: TppLabel;
    ppLabel647: TppLabel;
    ppLabel648: TppLabel;
    ppLabel649: TppLabel;
    ppLabel650: TppLabel;
    ppLabel651: TppLabel;
    ppLine89: TppLine;
    ppLabel652: TppLabel;
    ppLabel653: TppLabel;
    ppLabel654: TppLabel;
    ppLabel655: TppLabel;
    ppLabel656: TppLabel;
    ppLabel657: TppLabel;
    ppLabel658: TppLabel;
    ppLabel659: TppLabel;
    ppLabel660: TppLabel;
    ppLabel661: TppLabel;
    ppDBText395: TppDBText;
    ppDBText396: TppDBText;
    ppDBText397: TppDBText;
    ppDBText398: TppDBText;
    ppDBText399: TppDBText;
    ppDBText400: TppDBText;
    ppDBText401: TppDBText;
    ppDBText402: TppDBText;
    ppDBText403: TppDBText;
    ppDBText404: TppDBText;
    ppDBText405: TppDBText;
    ppDBText406: TppDBText;
    ppDBText407: TppDBText;
    ppLabel662: TppLabel;
    ppDBText408: TppDBText;
    ppLabel663: TppLabel;
    ppDBText409: TppDBText;
    ppLabel664: TppLabel;
    ppDBText410: TppDBText;
    ppLabel665: TppLabel;
    ppLabel666: TppLabel;
    ppLabel667: TppLabel;
    ppLabel668: TppLabel;
    ppLabel669: TppLabel;
    ppLabel670: TppLabel;
    ppLabel671: TppLabel;
    ppDetailBand14: TppDetailBand;
    ppDBText411: TppDBText;
    ppDBText412: TppDBText;
    ppDBText413: TppDBText;
    ppDBText414: TppDBText;
    ppDBText415: TppDBText;
    ppDBText416: TppDBText;
    ppDBText417: TppDBText;
    ppFooterBand14: TppFooterBand;
    ppLabel672: TppLabel;
    ppLabel673: TppLabel;
    ppDBText418: TppDBText;
    ppLabel674: TppLabel;
    ppLabel675: TppLabel;
    ppDBText419: TppDBText;
    ppDBText420: TppDBText;
    ppDBText421: TppDBText;
    ppLabel676: TppLabel;
    ppDBText422: TppDBText;
    ppLabel677: TppLabel;
    ppDBText423: TppDBText;
    ppLabel678: TppLabel;
    ppDBText424: TppDBText;
    ppLabel679: TppLabel;
    ppDBText425: TppDBText;
    ppLabel680: TppLabel;
    ppLine90: TppLine;
    ppLabel681: TppLabel;
    ppLine91: TppLine;
    ppLabel682: TppLabel;
    ppLabel683: TppLabel;
    ppLabel684: TppLabel;
    ppLabel685: TppLabel;
    ppLabel686: TppLabel;
    ppLabel687: TppLabel;
    ppLabel688: TppLabel;
    ppLabel689: TppLabel;
    ppLabel690: TppLabel;
    ppLabel691: TppLabel;
    ppLabel692: TppLabel;
    ppLabel693: TppLabel;
    ppLabel694: TppLabel;
    ppLabel695: TppLabel;
    ppLabel696: TppLabel;
    ppLabel697: TppLabel;
    ppDBText426: TppDBText;
    ppLine92: TppLine;
    ppLine93: TppLine;
    ppLine94: TppLine;
    ppDBText427: TppDBText;
    ppLabel698: TppLabel;
    ppLabel699: TppLabel;
    ppDBText429: TppDBText;
    ppLine95: TppLine;
    raCodeModule14: TraCodeModule;
    ppParameterList14: TppParameterList;
    rptOrc_B: TppReport;
    ppTitleBand1: TppTitleBand;
    ppDBText428: TppDBText;
    ppDBText430: TppDBText;
    ppDBText431: TppDBText;
    ppLabel700: TppLabel;
    ppLabel701: TppLabel;
    ppLabel702: TppLabel;
    ppDBText432: TppDBText;
    ppLabel703: TppLabel;
    ppDBText433: TppDBText;
    ppLabel704: TppLabel;
    ppDBText434: TppDBText;
    ppLine96: TppLine;
    ppLine97: TppLine;
    ppLabel705: TppLabel;
    ppLabel706: TppLabel;
    ppLabel707: TppLabel;
    ppLabel708: TppLabel;
    ppLabel709: TppLabel;
    ppLabel710: TppLabel;
    ppDetailBand15: TppDetailBand;
    ppDBText435: TppDBText;
    ppDBText436: TppDBText;
    ppDBText437: TppDBText;
    ppDBText438: TppDBText;
    ppDBText439: TppDBText;
    ppLabel711: TppLabel;
    ppLabel712: TppLabel;
    ppSummaryBand1: TppSummaryBand;
    ppLine98: TppLine;
    ppLabel713: TppLabel;
    ppLabel714: TppLabel;
    ppLine99: TppLine;
    ppLine100: TppLine;
    ppLabel715: TppLabel;
    ppSystemVariable14: TppSystemVariable;
    ppLabel716: TppLabel;
    ppDBText440: TppDBText;
    ppLabel717: TppLabel;
    ppDBText441: TppDBText;
    ppLabel741: TppLabel;
    ppDBText447: TppDBText;
    ppLabel742: TppLabel;
    ppDBText448: TppDBText;
    ppLabel743: TppLabel;
    ppDBText449: TppDBText;
    ppParameterList15: TppParameterList;
    rptOrc_F: TppReport;
    ppHeaderBand15: TppHeaderBand;
    ppLabel725: TppLabel;
    ppLabel718: TppLabel;
    ppLabel719: TppLabel;
    ppLabel720: TppLabel;
    ppLabel721: TppLabel;
    ppLabel722: TppLabel;
    ppLabel723: TppLabel;
    ppLabel726: TppLabel;
    ppLabel727: TppLabel;
    ppLabel728: TppLabel;
    ppLabel729: TppLabel;
    ppLabel730: TppLabel;
    ppLabel731: TppLabel;
    ppLabel732: TppLabel;
    ppLabel733: TppLabel;
    ppLabel734: TppLabel;
    ppLabel736: TppLabel;
    ppLabel737: TppLabel;
    ppLabel738: TppLabel;
    ppLabel739: TppLabel;
    ppLabel740: TppLabel;
    ppDetailBand16: TppDetailBand;
    ppDBText442: TppDBText;
    ppDBText443: TppDBText;
    ppLabel724: TppLabel;
    ppDBText444: TppDBText;
    ppDBText445: TppDBText;
    ppFooterBand15: TppFooterBand;
    ppLabel735: TppLabel;
    ppDBText446: TppDBText;
    ppDBText450: TppDBText;
    ppArchiveReader1: TppArchiveReader;
    procedure ppDBText32GetText(Sender: TObject; var Text: String);
    procedure ppDBText63GetText(Sender: TObject; var Text: String);
    procedure ppLabel69GetText(Sender: TObject; var Text: String);
    procedure ppLabel71GetText(Sender: TObject; var Text: String);
    procedure ppLabel73GetText(Sender: TObject; var Text: String);
    procedure ppLabel58GetText(Sender: TObject; var Text: String);
    procedure ppLabel74GetText(Sender: TObject; var Text: String);
    procedure ppLabel75GetText(Sender: TObject; var Text: String);
    procedure ppLabel76GetText(Sender: TObject; var Text: String);
    procedure ppLabel77GetText(Sender: TObject; var Text: String);
    procedure ppLabel78GetText(Sender: TObject; var Text: String);
    procedure ppLabel79GetText(Sender: TObject; var Text: String);
    procedure ppLabel80GetText(Sender: TObject; var Text: String);
    procedure ppLabel81GetText(Sender: TObject; var Text: String);
    procedure ppLabel82GetText(Sender: TObject; var Text: String);
    procedure ppLabel83GetText(Sender: TObject; var Text: String);
    procedure ppLabel84GetText(Sender: TObject; var Text: String);
    procedure ppLabel85GetText(Sender: TObject; var Text: String);
    procedure ppLabel86GetText(Sender: TObject; var Text: String);
    procedure ppLabel87GetText(Sender: TObject; var Text: String);
    procedure ppLabel88GetText(Sender: TObject; var Text: String);
    procedure DataModuleCreate(Sender: TObject);
    procedure ppLabel89GetText(Sender: TObject; var Text: String);
    procedure ppLabel90GetText(Sender: TObject; var Text: String);
    procedure ppLabel91GetText(Sender: TObject; var Text: String);
    procedure ppLabel292GetText(Sender: TObject; var Text: String);
    procedure ppLabel296GetText(Sender: TObject; var Text: String);
    procedure ppLabel297GetText(Sender: TObject; var Text: String);
    procedure ppLabel300GetText(Sender: TObject; var Text: String);
    procedure ppLabel301GetText(Sender: TObject; var Text: String);
    procedure ppLabel294GetText(Sender: TObject; var Text: String);
    procedure ppDBText191GetText(Sender: TObject; var Text: String);
    procedure ppLabel476GetText(Sender: TObject; var Text: String);
    procedure ppDBText270GetText(Sender: TObject; var Text: String);
    procedure ppDBText279GetText(Sender: TObject; var Text: String);
    procedure ppDBText310GetText(Sender: TObject; var Text: String);
    procedure ppDBText210GetText(Sender: TObject; var Text: String);
    procedure ppDBText360GetText(Sender: TObject; var Text: String);
    procedure ppDBText384GetText(Sender: TObject; var Text: String);
    procedure ppLabel615GetText(Sender: TObject; var Text: String);
    procedure ppDBText394GetText(Sender: TObject; var Text: String);
    procedure ppDBText428GetText(Sender: TObject; var Text: String);
    procedure ppLabel724GetText(Sender: TObject; var Text: String);
    procedure ppLabel725GetText(Sender: TObject; var Text: String);
    procedure ppLabel728GetText(Sender: TObject; var Text: String);
    procedure ppLabel729GetText(Sender: TObject; var Text: String);
    procedure ppLabel730GetText(Sender: TObject; var Text: String);
    procedure ppLabel731GetText(Sender: TObject; var Text: String);
    procedure ppLabel719GetText(Sender: TObject; var Text: String);
    procedure ppLabel718GetText(Sender: TObject; var Text: String);
    procedure ppLabel732GetText(Sender: TObject; var Text: String);
    procedure ppLabel733GetText(Sender: TObject; var Text: String);
    procedure ppLabel726GetText(Sender: TObject; var Text: String);
    procedure ppLabel727GetText(Sender: TObject; var Text: String);
    procedure ppLabel736GetText(Sender: TObject; var Text: String);
    procedure ppLabel737GetText(Sender: TObject; var Text: String);
    procedure ppLabel738GetText(Sender: TObject; var Text: String);
    procedure ppLabel739GetText(Sender: TObject; var Text: String);
    procedure ppLabel740GetText(Sender: TObject; var Text: String);
    procedure ppLabel720GetText(Sender: TObject; var Text: String);
    procedure ppLabel721GetText(Sender: TObject; var Text: String);
    procedure ppLabel734GetText(Sender: TObject; var Text: String);
    procedure ppLabel722GetText(Sender: TObject; var Text: String);
    procedure ppLabel723GetText(Sender: TObject; var Text: String);
  private
    { Private declarations }
  public
    { Public declarations }
  end;

var
  dmImpCI: TdmImpCI;
  Parametro: TParametros_Venda;

implementation

uses uGlobal, uDmPrincipal;

{$R *.dfm}

procedure TdmImpCI.ppDBText32GetText(Sender: TObject; var Text: String);
begin
   Text := cdsOrcamentoEND_EMPRESA.Value + ' - ' + cdsOrcamentoCIDADE_EMP.Value;
end;

procedure TdmImpCI.ppDBText63GetText(Sender: TObject; var Text: String);
begin
   Text := CidadeEmpresa1
end;

procedure TdmImpCI.ppLabel69GetText(Sender: TObject; var Text: String);
begin
   Text := EstadoEmpresa1
end;

procedure TdmImpCI.ppLabel71GetText(Sender: TObject; var Text: String);
begin
   Text := CepEmpresa1
end;

procedure TdmImpCI.ppLabel73GetText(Sender: TObject; var Text: String);
begin
   Text := FoneEmpresa1;
end;

procedure TdmImpCI.ppLabel58GetText(Sender: TObject; var Text: String);
begin
   Text := cdsOrcamentoVENCIMEN01_VENDA.AsString + ' ' +  cdsOrcamentoVALOR01_VENDA.AsString;
end;

procedure TdmImpCI.ppLabel74GetText(Sender: TObject; var Text: String);
begin
   Text := cdsOrcamentoVENCIMEN02_VENDA.AsString + ' ' +  cdsOrcamentoVALOR02_VENDA.AsString;
end;

procedure TdmImpCI.ppLabel75GetText(Sender: TObject; var Text: String);
begin
   Text := cdsOrcamentoVENCIMEN03_VENDA.AsString + ' ' +  cdsOrcamentoVALOR03_VENDA.AsString;
end;

procedure TdmImpCI.ppLabel76GetText(Sender: TObject; var Text: String);
begin
   Text := cdsOrcamentoVENCIMEN04_VENDA.AsString + ' ' +  cdsOrcamentoVALOR04_VENDA.AsString;
end;

procedure TdmImpCI.ppLabel77GetText(Sender: TObject; var Text: String);
begin
   Text := cdsOrcamentoVENCIMEN05_VENDA.AsString + ' ' +  cdsOrcamentoVALOR05_VENDA.AsString;
end;

procedure TdmImpCI.ppLabel78GetText(Sender: TObject; var Text: String);
begin
   Text := cdsOrcamentoVENCIMEN06_VENDA.AsString + ' ' +  cdsOrcamentoVALOR06_VENDA.AsString;
end;

procedure TdmImpCI.ppLabel79GetText(Sender: TObject; var Text: String);
begin
   Text := cdsOrcamentoVENCIMEN07_VENDA.AsString + ' ' +  cdsOrcamentoVALOR07_VENDA.AsString;
end;

procedure TdmImpCI.ppLabel80GetText(Sender: TObject; var Text: String);
begin
   Text := cdsOrcamentoVENCIMEN08_VENDA.AsString + ' ' +  cdsOrcamentoVALOR08_VENDA.AsString;
end;

procedure TdmImpCI.ppLabel81GetText(Sender: TObject; var Text: String);
begin
   Text := cdsOrcamentoVENCIMEN09_VENDA.AsString + ' ' +  cdsOrcamentoVALOR09_VENDA.AsString;
end;

procedure TdmImpCI.ppLabel82GetText(Sender: TObject; var Text: String);
begin
   Text := cdsOrcamentoVENCIMEN10_VENDA.AsString + ' ' +  cdsOrcamentoVALOR10_VENDA.AsString;
end;

procedure TdmImpCI.ppLabel83GetText(Sender: TObject; var Text: String);
begin
   Text := cdsOrcamentoVENCIMEN11_VENDA.AsString + ' ' +  cdsOrcamentoVALOR11_VENDA.AsString;
end;

procedure TdmImpCI.ppLabel84GetText(Sender: TObject; var Text: String);
begin
   Text := cdsOrcamentoVENCIMEN12_VENDA.AsString + ' ' +  cdsOrcamentoVALOR12_VENDA.AsString;
end;

procedure TdmImpCI.ppLabel85GetText(Sender: TObject; var Text: String);
begin
   Text := cdsOrcamentoVENCIMEN13_VENDA.AsString + ' ' +  cdsOrcamentoVALOR13_VENDA.AsString;
end;

procedure TdmImpCI.ppLabel86GetText(Sender: TObject; var Text: String);
begin
   Text := cdsOrcamentoVENCIMEN14_VENDA.AsString + ' ' +  cdsOrcamentoVALOR14_VENDA.AsString;
end;

procedure TdmImpCI.ppLabel87GetText(Sender: TObject; var Text: String);
begin
   Text := cdsOrcamentoVENCIMEN15_VENDA.AsString + ' ' +  cdsOrcamentoVALOR15_VENDA.AsString;
end;

procedure TdmImpCI.ppLabel88GetText(Sender: TObject; var Text: String);
begin
   Text := Parametro.Msn_linha(1);
end;

procedure TdmImpCI.DataModuleCreate(Sender: TObject);
begin
   Parametro := TParametros_Venda.Create;
   Parametro.Carregar();
end;

procedure TdmImpCI.ppLabel89GetText(Sender: TObject; var Text: String);
begin
   Text := Parametro.Msn_linha(2);
end;

procedure TdmImpCI.ppLabel90GetText(Sender: TObject; var Text: String);
begin
   Text := Parametro.Msn_linha(3);
end;

procedure TdmImpCI.ppLabel91GetText(Sender: TObject; var Text: String);
begin
   Text := Parametro.Msn_linha(4);
end;

procedure TdmImpCI.ppLabel292GetText(Sender: TObject; var Text: String);
begin
   Text := 'PLANO 1: 1ª 30 dias - ' + DateToStr(cdsOrcamentoDATA_VENDA.Value + 30);
end;

procedure TdmImpCI.ppLabel296GetText(Sender: TObject; var Text: String);
begin
   Text := 'PLANO 2: 1ª 20 dias - ' + DateToStr(cdsOrcamentoDATA_VENDA.Value + 20);
end;

procedure TdmImpCI.ppLabel297GetText(Sender: TObject; var Text: String);
begin
   Text := '2ª 40 dias - ' + DateToStr(cdsOrcamentoDATA_VENDA.Value + 40);
end;

procedure TdmImpCI.ppLabel300GetText(Sender: TObject; var Text: String);
begin
   Text := 'PLANO 3: 1ª 15 dias - ' + DateToStr(cdsOrcamentoDATA_VENDA.Value + 15);
end;

procedure TdmImpCI.ppLabel301GetText(Sender: TObject; var Text: String);
begin
   Text := '2ª 30 dias - ' + DateToStr(cdsOrcamentoDATA_VENDA.Value + 30);
end;

procedure TdmImpCI.ppLabel294GetText(Sender: TObject; var Text: String);
begin
   Text := '3ª 45 dias - ' + DateToStr(cdsOrcamentoDATA_VENDA.Value + 45);
end;

procedure TdmImpCI.ppDBText191GetText(Sender: TObject; var Text: String);
begin
   Text := RazaoSocial1;
end;

procedure TdmImpCI.ppLabel476GetText(Sender: TObject; var Text: String);
begin
   Text := 'Telefone: ' + cdsOrcamentoFONE_EMP.Value
end;

procedure TdmImpCI.ppDBText270GetText(Sender: TObject; var Text: String);
begin
   Text := cdsOrcamentoENDERECO_CLIENTE.Value + ' - ' + cdsOrcamentoBAIRRO_CLIENTE.Value + ' - ' + cdsOrcamentoNOME_CIDADE.Value;
end;

procedure TdmImpCI.ppDBText279GetText(Sender: TObject; var Text: String);
begin
   Text := Parametro.Msn_linha(1);
end;

procedure TdmImpCI.ppDBText310GetText(Sender: TObject; var Text: String);
begin
   Text := cdsOrcamentoEND_EMPRESA.Value + ' - ' + cdsOrcamentoCIDADE_EMP.Value + ' * FONE: ' + cdsOrcamentoFONE_EMP.Value;
end;

procedure TdmImpCI.ppDBText210GetText(Sender: TObject; var Text: String);
begin
   Text := FloatToStrF(cdsItensOrcVALORBRUTO_IVENDAS.asFloat + cdsItensOrcDESCONTO_IVENDAS.AsFloat,ffFixed,18,2);
end;

procedure TdmImpCI.ppDBText360GetText(Sender: TObject; var Text: String);
begin
   if cdsItensOrcDESCONTO_IVENDAS.AsFloat > 0 then
      Text := FloatToStrF(cdsItensOrcDESCONTO_IVENDAS.AsFloat * 100 / (cdsItensOrcVALORBRUTO_IVENDAS.asFloat + cdsItensOrcDESCONTO_IVENDAS.AsFloat),ffFixed,18,2) + '%'
   else
      Text := '';
end;

procedure TdmImpCI.ppDBText384GetText(Sender: TObject; var Text: String);
begin
   if Master1 = 'T' then
      Text := FloatToStrF(cdsItensOrcPRECO_CUSTO_PRODUTO.AsFloat,ffFixed,18,2)
   else
      Text := '';
end;

procedure TdmImpCI.ppLabel615GetText(Sender: TObject; var Text: String);
begin
   if Master1 = 'T' then
      Text := 'Preço Custo'
   else
      Text := '';
end;

procedure TdmImpCI.ppDBText394GetText(Sender: TObject; var Text: String);
begin
   Text := Parametro.Msn_linha(1);
end;

procedure TdmImpCI.ppDBText428GetText(Sender: TObject; var Text: String);
begin
   Text := cdsOrcamentoEMPRESA.Value + ' - ' + cdsOrcamentoFONE_EMP.Value;
end;

procedure TdmImpCI.ppLabel724GetText(Sender: TObject; var Text: String);
begin
   Text := StrZero(cdsItensOrcPRODUTO_IVENDA.AsString,6) + ' ' + cdsItensOrcDESCRICAO_IVENDAS.Value;
end;

procedure TdmImpCI.ppLabel725GetText(Sender: TObject; var Text: String);
begin
   Text := StrZero(cdsOrcamentoCODIGO_CLIENTE.AsString,6) + '-' + cdsOrcamentoNOME_CLIENTE.Value;
end;

procedure TdmImpCI.ppLabel728GetText(Sender: TObject; var Text: String);
begin
   text := StrZero(cdsOrcamentoCODIGO_VENDA.AsString,6);
end;

procedure TdmImpCI.ppLabel729GetText(Sender: TObject; var Text: String);
var
   Dia,mes,ano:word;
begin
   DecodeDate(cdsOrcamentoDATA_VENDA.AsDateTime,ano,mes,dia);
   text := StrZero(IntToStr(dia),2);
end;

procedure TdmImpCI.ppLabel730GetText(Sender: TObject; var Text: String);
var
   Dia,mes,ano:word;
begin
   DecodeDate(cdsOrcamentoDATA_VENDA.AsDateTime,ano,mes,dia);
   text := StrZero(IntToStr(mes),2);
end;

procedure TdmImpCI.ppLabel731GetText(Sender: TObject; var Text: String);
var
   Dia,mes,ano:word;
begin
   DecodeDate(cdsOrcamentoDATA_VENDA.AsDateTime,ano,mes,dia);
   text := IntToStr(ano);
end;

procedure TdmImpCI.ppLabel719GetText(Sender: TObject; var Text: String);
begin
   Text := cdsOrcamentoCNPJ_CLIENTE.AsString;
end;

procedure TdmImpCI.ppLabel718GetText(Sender: TObject; var Text: String);
begin
   Text := cdsOrcamentoENDERECO_CLIENTE.AsString;
end;

procedure TdmImpCI.ppLabel732GetText(Sender: TObject; var Text: String);
begin
   Text := cdsOrcamentoNOME_CIDADE.AsString + '-' + cdsOrcamentoESTADO_CLIENTE.AsString;
end;

procedure TdmImpCI.ppLabel733GetText(Sender: TObject; var Text: String);
begin
 Text := cdsOrcamentoINSCRICAO_CLIENTE.AsString;
end;

procedure TdmImpCI.ppLabel726GetText(Sender: TObject; var Text: String);
begin
   Text := cdsOrcamentoFORMA_PAGAMENTO.Value;
end;

procedure TdmImpCI.ppLabel727GetText(Sender: TObject; var Text: String);
begin
   if cdsOrcamentoVALOR01_VENDA.AsFloat > 0 then
      text := cdsOrcamentoVENCIMEN01_VENDA.AsString + ' ' + FloatToStrF(cdsOrcamentoVALOR01_VENDA.AsFloat,ffFixed,18,2);
end;

procedure TdmImpCI.ppLabel736GetText(Sender: TObject; var Text: String);
begin
      if cdsOrcamentoVALOR02_VENDA.AsFloat > 0 then
      text := cdsOrcamentoVENCIMEN02_VENDA.AsString + ' ' + FloatToStrF(cdsOrcamentoVALOR02_VENDA.AsFloat,ffFixed,18,2);
end;

procedure TdmImpCI.ppLabel737GetText(Sender: TObject; var Text: String);
begin
      if cdsOrcamentoVALOR03_VENDA.AsFloat > 0 then
      text := cdsOrcamentoVENCIMEN03_VENDA.AsString + ' ' + FloatToStrF(cdsOrcamentoVALOR03_VENDA.AsFloat,ffFixed,18,2);
end;

procedure TdmImpCI.ppLabel738GetText(Sender: TObject; var Text: String);
begin
      if cdsOrcamentoVALOR04_VENDA.AsFloat > 0 then
      text := cdsOrcamentoVENCIMEN04_VENDA.AsString + ' ' + FloatToStrF(cdsOrcamentoVALOR04_VENDA.AsFloat,ffFixed,18,2);
end;

procedure TdmImpCI.ppLabel739GetText(Sender: TObject; var Text: String);
begin
      if cdsOrcamentoVALOR05_VENDA.AsFloat > 0 then
      text := cdsOrcamentoVENCIMEN05_VENDA.AsString + ' ' + FloatToStrF(cdsOrcamentoVALOR05_VENDA.AsFloat,ffFixed,18,2);
end;

procedure TdmImpCI.ppLabel740GetText(Sender: TObject; var Text: String);
begin
   if cdsOrcamentoVALOR06_VENDA.AsFloat > 0 then
      text := cdsOrcamentoVENCIMEN06_VENDA.AsString + ' ' + FloatToStrF(cdsOrcamentoVALOR06_VENDA.AsFloat,ffFixed,18,2);
end;

procedure TdmImpCI.ppLabel720GetText(Sender: TObject; var Text: String);
begin
   Text := cdsOrcamentoCOB_ENDERECO_CLIENTE.Value;
end;

procedure TdmImpCI.ppLabel721GetText(Sender: TObject; var Text: String);
begin
   Text := cdsOrcamentoCOB_NOME_CIDADE.Value;
end;

procedure TdmImpCI.ppLabel734GetText(Sender: TObject; var Text: String);
begin
   Text := cdsOrcamentoBANCO1_CLIENTE.Value;
end;

procedure TdmImpCI.ppLabel722GetText(Sender: TObject; var Text: String);
begin
   Text := cdsOrcamentoDATA_VENDA.AsString;
end;

procedure TdmImpCI.ppLabel723GetText(Sender: TObject; var Text: String);
begin
   Text := cdsOrcamentoENDERECO_CLIENTE.Value;
end;

end.
